name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        name: Check out code
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to GH registry
        with:
          image: guiodsc/tcc_extensao
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Get SHORT SHA
        id: shortsha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - uses: fjogeleit/http-request-action@v1
        name: Deploy
        with:
          url: ${{ secrets.WEBHOOK_URL }}?tag=main-${{ steps.shortsha.outputs.sha_short }}
          method: 'POST'
