name: Build & Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tcc_extensaouniversitaria/app


jobs:
  build-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        name: Check out code
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to GH registry
        with:
          image: tcc_extensaouniversitaria/app
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: fjogeleit/http-request-action@v1
        name: Deploy
        with:
          url: ${{ secrets.WEBHOOK_URL }}?tag=main-${GITHUB_SHA::7}
          method: 'POST'
